# Generated by Django 4.2.4 on 2023-08-27 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailingsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='отправка')),
                ('message_subject', models.CharField(max_length=200, verbose_name='тема сообщения')),
                ('text_message', models.TextField(verbose_name='тело сообщения')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsetting', verbose_name='настройки')),
            ],
            options={
                'verbose_name': 'сообщение рассылки',
                'verbose_name_plural': 'сообщения рассылки',
            },
        ),
    ]
